"""create meal plan tables

Revision ID: 80fa891a5f11
Revises: ddb7ad3663c8
Create Date: 2026-06-19 12:41:07.866740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '80fa891a5f11'
down_revision: Union[str, Sequence[str], None] = 'ddb7ad3663c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal_plans',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('patient_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('dietitian_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dietitian_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meal_plan_days',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('meal_plan_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['meal_plan_id'], ['meal_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meal_plan_items',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('meal_plan_day_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('food_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('meal_slot', sa.Enum('breakfast', 'mid_morning', 'lunch', 'evening_snack', 'dinner', 'bedtime', name='mealslot'), nullable=False),
    sa.Column('quantity_g', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ),
    sa.ForeignKeyConstraint(['meal_plan_day_id'], ['meal_plan_days.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meal_plan_items')
    op.drop_table('meal_plan_days')
    op.drop_table('meal_plans')
    # ### end Alembic commands ###
