"""create patient tables

Revision ID: ddb7ad3663c8
Revises: 0887e965ede2
Create Date: 2026-06-18 01:49:59.011987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ddb7ad3663c8'
down_revision: Union[str, Sequence[str], None] = '0887e965ede2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('dietitian_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', 'other', name='gender'), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('current_weight_kg', sa.Float(), nullable=True),
    sa.Column('target_weight_kg', sa.Float(), nullable=True),
    sa.Column('medical_conditions', sa.Text(), nullable=True),
    sa.Column('dietary_preferences', sa.Text(), nullable=True),
    sa.Column('goal', sa.Enum('weight_loss', 'weight_gain', 'muscle_gain', 'maintenance', 'clinical_management', name='goal'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dietitian_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient_measurements',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('patient_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('bmi', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patient_measurements')
    op.drop_table('patients')
    # ### end Alembic commands ###
